name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest  # Alterado para Ubuntu

    steps:
    - name: Download Ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract Ngrok
      run: tar -xvzf ngrok.tgz

    - name: Authenticate Ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install RDP and Enable Service
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Set Password for Default User
      run: echo "runner:123456" | sudo chpasswd

    - name: Allow RDP Through Firewall
      run: sudo ufw allow 3389

    - name: Create Tunnel with Ngrok
      run: ./ngrok tcp 3389
